export enum routes {
  ROUTE_BASE = '/api',
  ROUTE_PEOPLE = '/api/people',
  ROUTE_PEOPLE_ID = '/api/people/',
  ROUTE_PEOPLE_PAGE = '/api/people?page=',
  ROUTE_PEOPLE_SEARCH = '/api/people?search=',
  ROUTE_FILM = '/api/films',
  ROUTE_FILM_ID = '/api/films/',
  ROUTE_FILM_PAGE = '/api/films?page=',
  ROUTE_FILM_SEARCH = '/api/films?search=',
  ROUTE_STARSHIP = '/api/starships',
  ROUTE_STARSHIP_ID = '/api/starships/',
  ROUTE_STARSHIP_PAGE = '/api/starships?page=',
  ROUTE_STARSHIP_SEARCH = '/api/starships?search=',
  ROUTE_PLANET = '/api/planets',
  ROUTE_PLANET_ID = '/api/planets/',
  ROUTE_PLANET_PAGE = '/api/planets?page=',
  ROUTE_PLANET_SEARCH = '/api/planets?search=',
}
